### ISSUE TITLE
cannot install this package?

### ISSUE THREAD

**Issue by mo** [DavertMik/codeceptjs-webdriverio#1]
$ mkdir abc
$ cd abc
$ npm init -f
$ npm install --save-dev codeceptjs-webdriverio
npm WARN abc@1.0.0 No description
npm WARN abc@1.0.0 No repository field.

npm ERR! path /home/molsson/abc/node_modules/codeceptjs-webdriverio/node_modules/.bin/codeceptjs
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/home/molsson/abc/node_modules/codeceptjs-webdriverio/node_modules/.bin/codeceptjs'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/molsson/.npm/_logs/2017-06-18T13_33_03_454Z-debug.log

If I install first "codeceptjs" and then "webdriverio" separately, it works just fine though.

$ node --version
v7.7.2
$ npm --version
5.0.3

**Comment by fatso83** [comment]
Yeah, getting the same error. There seems to be a bug in how the right `node_modules` package is located. The layout would only be correct with version 2 of NPM, that had a hierarchical package layout structure. Nowadays you cannot assume that.

**Comment by Amdingo** [comment]
+1 on this hopefully @DavertMik can provide some insight or update the lookup for .bin/

**Comment by DavertMik** [comment]
Sorry, for the delay. I will take a look.

**Comment by andreluizbnu** [comment]
+1 - Same error here.

**Comment by DavertMik** [comment]
Thanks, this was fixed in 1.1.0 release. Please update
Yes, I was using old npm 3 and didn't get notice

**Comment by mo** [comment]
thanks for the fix @DavertMik
